version: 2
sources:
  - name: airbyte_internal
    tables:
      # Fact Tables
      - name: raw_raw__stream_bahigo_altpay_deposit

      # Dimension Tables
      - name: raw_raw__stream_bahigo_altpay_currency
      - name: raw_raw__stream_bahigo_altpay_paymentservice